export interface usuario {
    dni_cliente: number,
    dv_cliente: number,
    nombre_cliente: string,
    apellidopaterno_cliente: string,
    apellidomaterno_cliente: string,
    e_mail_cliente: string,
    celular_cliente: string,
    telefono_cliente: string,
    direccion_cliente: string,
    vigente_cliente: number,
    tipodocumento_cliente: string,
    fechacreacion_cliente: string,
    mediollegada_cliente: string,
    idProvincia: number,
    idDepartamento: number,
    idDistrito:number,
    id_cliente: number,
    id_usuario: number,
}